### ISSUE TITLE
new version of tensorflow

### ISSUE THREAD

**Issue by seudnuredin** [ayoungprogrammer/num2vec#1]
Hi ayoungprogrammer, Can you plz help me by updating your repo to the new version of tensorflow. I have tried several ways like 'import tensorflow.compat.v1 as tf'
but it didn't work and i was editing your code for days but i couldn't run it with the new tensorflow, this was my error:
Traceback (most recent call last):
  File "C:/Users/pc/Desktop/num2vec-master/eval.py", line 6, in <module>
    seq_model.load()
  File "C:\Users\pc\Desktop\num2vec-master\rnn_seq.py", line 184, in load
    self.saver.restore(self.sess, model_fi)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\training\saver.py", line 1289, in restore
    if not checkpoint_management.checkpoint_exists_internal(checkpoint_prefix):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\training\checkpoint_management.py", line 383, in checkpoint_exists_internal
    if file_io.get_matching_files(pathname):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 350, in get_matching_files
    return get_matching_files_v2(filename)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 408, in get_matching_files_v2
    for matching_filename in _pywrap_file_io.GetMatchingFiles(
tensorflow.python.framework.errors_impl.NotFoundError: FindFirstFile failed for: saved : The system cannot find the path specified.
; No such process

Process finished with exit code 1

**Comment by dasdibye** [comment]
Hi-

This is pretty interesting and I am looking for a direct num -> embedding table which I need to use for my project. How should I modify your code to get that ?

-Thx
Dibyendu
